name: gurps_incantation_magic_webapp
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: jeff <email@example.com>

environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  built_collection: ^3.1.1
  quiver: '>=0.29.0 <0.30.0'
  gurps_dart:
    path: ../gurps_dart
  gurps_incantation_magic_model:
      path: ../gurps-incantation-magic-dart

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
