name: gurps_incantation_magic_webapp
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: jeff <email@example.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  built_collection: ^4.3.2
  quiver: ^2.1.5
  gurps_incantation_magic_model:
    version: ^1.0.1
    git:
      url: https://github.com/mjeffw/gurps-incantation-magic-dart.git
  gurps_dart:
    version: ^1.4.4
    git:
      url: https://github.com/mjeffw/gurps_dart.git

dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.11.1
  build_test: ^1.3.6
  build_web_compilers: ^2.12.2
  test: ^1.15.7
